// Copyright (c) 2023 Kimball Thurston
// SPDX-License-Identifier: MIT

#pragma once

#define ALDER_VERSION_MAJOR 0
#define ALDER_VERSION_MINOR 0
#define ALDER_VERSION_PATCH 1

#define ALDER_STRINGIFY(x) ALDER_STRINGIFY_EXPAND(x)
#define ALDER_STRINGIFY_EXPAND(x) #x

#define ALDER_VERSION_STRING ALDER_STRINGIFY(ALDER_VERSION_MAJOR) "." ALDER_STRINGIFY(ALDER_VERSION_MAJOR) "." ALDER_STRINGIFY(ALDER_VERSION_PATCH)

